version: '3'
services:
  eureka:
    image: eureka
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    tty: true
    restart: on-failure
    container_name: eureka
    networks:
      - nistagram-network

  #zuul:
    #image: zuul
    #build:
      #context: ./Zuul
      #dockerfile: Dockerfile
    #ports:
      #- "8080:8080"
    #tty: true
    #restart: on-failure
    #container_name: zuul
    #depends_on:
      #- eureka
    #environment:
      #- REGISTRY_HOST=eureka
    #networks:
      #- nistagram-network


  #authservice:
   # image: authservice
    #build:
     # context: ./AuthService
      #dockerfile: Dockerfile
    #ports:
     # - "8090:8090"
    #tty: true
    #restart: on-failure
    #container_name: authservice
    #depends_on:
     # - eureka
    #environment:
     # - REGISTRY_HOST=eureka
    #networks:
     # - nistagram-network


  postservice:
    image: postservice
    build:
      context: ./PostService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    tty: true
    restart: on-failure
    container_name: postservice
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - nistagram-network
    volumes:
      - C:/Users/Dragan/.m2:/root/.m2

  #followerservice:
    #image: followerservice
    #build:
      #context: ./Followerservice
      #dockerfile: Dockerfile
    #ports:
      #- "8082:8082"
    #tty: true
    #restart: on-failure
    #container_name: followerservice
    #depends_on:
      #- eureka
    #environment:
      #- REGISTRY_HOST=eureka
    #networks:
      #- nistagram-network

  #settingsservice:
    #image: settingsservice
    #build:
      #context: ./settingsservice
      #dockerfile: Dockerfile
    #ports:
      #- "8084:8084"
    #tty: true
    #restart: on-failure
    #container_name: settingsservice
    #depends_on:
      #- eureka
    #environment:
      #- REGISTRY_HOST=eureka
    #networks:
      #- nistagram-network 

networks:
  nistagram-network:
    driver: bridge