version: '3'
services:
  eureka:
    image: eureka
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    tty: true
    restart: on-failure
    container_name: eureka
    networks:
      - nistagram-network

  settingsservice:
    image: settingsservice
    build:
      context: ./settingsservice
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    tty: true
    restart: on-failure
    container_name: settingsservice
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - nistagram-network 

networks:
  nistagram-network:
    driver: bridge
